[package]
name = "anisystemd"
version = "0.1.0"
edition = "2021"

[dependencies]
anicore = { path = "../anicore" }
tokio = { workspace = true }
anyhow = "1.0"
dotenv = "0.15"
notify = "6.1"
tracing = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
libsystemd = "0.5"

